### ISSUE TITLE
Set readOnlyRootFilesystem to true for Keycloak Container in StatefulSet

### ISSUE THREAD

**Issue by AmithSAI007** [AmithSAI007/prj-cinematik-keycloak-authorization#11]
### **Issue Title**  
Set `readOnlyRootFilesystem` to `true` for Keycloak Container in StatefulSet

---

### **Description**  
The `keycloak` container in the Keycloak StatefulSet currently does not set the `securityContext.readOnlyRootFilesystem` field to `true`. This poses a security risk as it allows write access to the container's root filesystem, increasing the attack surface.

---

### **Vulnerability Details**  
- **Artifact:** `manifests/deployment/keycloak-statefulset.yaml`  
- **Type:** Kubernetes  
- **Vulnerability ID:** KSV014  
- **Severity:** HIGH  
- **Message:** Container `keycloak` of StatefulSet `keycloak` should set `securityContext.readOnlyRootFilesystem` to `true`.  
- **Link:** [KSV014 Documentation](https://example.com/ksv014-docs)  

---

### **Proposed Solution**  
1. Update the `keycloak` container's `securityContext` configuration in the StatefulSet manifest to include:  
   ```yaml
   securityContext:
     readOnlyRootFilesystem: true
   ```

2. Apply the updated StatefulSet manifest to the Kubernetes cluster.
3. Test the Keycloak application to ensure functionality is unaffected by the change.

---

### **Additional Details***

- Setting readOnlyRootFilesystem: true ensures that the container's root filesystem is immutable, preventing attackers from tampering with the file system during runtime.

---

### **Acceptance Criteria**

- [ ] The `securityContext.readOnlyRootFilesystem` field is set to `true` for the `keycloak` container.
- [ ] The updated StatefulSet is applied to the cluster.
- [ ] Functionality of the Keycloak application is verified to remain intact.
- [ ] Security scan passes without any KSV014 warnings.

---

### **Dependencies**
NONE

---

###**Tasks**

- [ ] Add `securityContext.readOnlyRootFilesystem: true` to the `keycloak` container in the StatefulSet manifest.
- [ ] Apply the updated manifest to the Kubernetes cluster.
- [ ] Test the Keycloak application to confirm functionality.
- [ ] Document the security enhancement in the deployment README.

---

### **References**  
- [Kubernetes Best Practices for Security Context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/)
