### ISSUE TITLE
Seccomp Profile Missing in Keycloak StatefulSet

### ISSUE THREAD

**Issue by AmithSAI007** [AmithSAI007/prj-cinematik-keycloak-authorization#9]
### **Issue: Seccomp Profile Missing in Keycloak StatefulSet**  
**Severity:** Medium  
**Priority:** High  
**Type:** Security  

#### **Description**  
The `keycloak-chart` container in the `StatefulSet` Helm template does not specify a seccomp profile. This can lead to potential security vulnerabilities by allowing unrestricted system calls within the container.  
The issue has been flagged by automated security tools with the vulnerability ID **KSV104**.

#### **Impact**  
- **Risk:** Containers without seccomp profiles are more susceptible to exploitation via system calls.
- **Compliance:** Fails to meet Kubernetes best practices for container security.

---

#### **Steps to Reproduce**  
1. Deploy the current version of the `keycloak-chart` Helm chart.  
2. Scan the Kubernetes configuration using a security tool like Trivy or Kube-score.  
3. Observe the **KSV104** warning for the missing seccomp profile.  

---

#### **Proposed Solution**  
1. Add a `securityContext` block to the `keycloak-chart` container specification in the `statefulset.yaml` file.  
2. Configure the `seccompProfile` with the `RuntimeDefault` value to enforce Kubernetes' default seccomp profile.

**Updated YAML Snippet:**
```yaml
securityContext:
  seccompProfile:
    type: RuntimeDefault
```

### **Additional Details**  
- Reference: [Kubernetes Documentation on Seccomp](https://kubernetes.io/docs/tutorials/security/seccomp/)  

---

### **Acceptance Criteria**  
- [ ] The `securityContext` block with `seccompProfile` is added to the container specification.  
- [ ] The Helm chart passes all security scans without any **KSV104** or similar warnings.  
- [ ] Deployment is tested in staging, confirming no regression or compatibility issues.

---

### **Dependencies**  
- None.  

---

### **Tasks**  
- [ ] Update `statefulset.yaml` to include `seccompProfile`.  
- [ ] Add tests or validations for the `securityContext`.  
- [ ] Test the deployment in staging.  
- [ ] Document the changes in the Helm chart README.  

---

### **References**  
- [Kubernetes Seccomp Configuration Guide](https://kubernetes.io/docs/tutorials/security/seccomp/)
